// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEr-GBmQHrLKfAsu-0-UytYGbUuJL1p8g',
    appId: '1:205902735027:web:129b273fcdd8bdc8f6f2c6',
    messagingSenderId: '205902735027',
    projectId: 'test-login-3a437',
    authDomain: 'test-login-3a437.firebaseapp.com',
    storageBucket: 'test-login-3a437.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG_B87dHOl5dBJrsul5h7VCkxxSJc2XSA',
    appId: '1:205902735027:android:400e17776320e3dcf6f2c6',
    messagingSenderId: '205902735027',
    projectId: 'test-login-3a437',
    storageBucket: 'test-login-3a437.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNRMaNDjYPSmqrGzKxdY1mNL6GtAE8yt4',
    appId: '1:205902735027:ios:c4966d777c8d5b30f6f2c6',
    messagingSenderId: '205902735027',
    projectId: 'test-login-3a437',
    storageBucket: 'test-login-3a437.firebasestorage.app',
    iosBundleId: 'com.example.loginTestKdrz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNRMaNDjYPSmqrGzKxdY1mNL6GtAE8yt4',
    appId: '1:205902735027:ios:c4966d777c8d5b30f6f2c6',
    messagingSenderId: '205902735027',
    projectId: 'test-login-3a437',
    storageBucket: 'test-login-3a437.firebasestorage.app',
    iosBundleId: 'com.example.loginTestKdrz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEr-GBmQHrLKfAsu-0-UytYGbUuJL1p8g',
    appId: '1:205902735027:web:502f8642203ae916f6f2c6',
    messagingSenderId: '205902735027',
    projectId: 'test-login-3a437',
    authDomain: 'test-login-3a437.firebaseapp.com',
    storageBucket: 'test-login-3a437.firebasestorage.app',
  );
}
